# ---

- name: 'create tmp directory'
  file:
    path: ~/tmp
    state: directory
  tags:
    - pacaur
    - pacaur.tmp

# ---

- name: 'import pacaur gpg key'
  shell: "gpg --recv-keys --yes {{ gpg_key }}"
  with_items: "{{ pacaur_gpg_keys }}"
  loop_control:
    loop_var: gpg_key
  tags:
    - pacaur
    - pacaur.gpg

## ---
#- name: 'download pacaur'
#  get_url:
#    url: 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur'
#    dest: '~/tmp/PKGBUILD-pacaur'
#  tags:
#    - pacaur
#    - pacaur.pacaur
#
#- name: 'build pacaur'
#  shell: 'makepkg -sfp PKGBUILD-pacaur --noconfirm'
#  args:
#    chdir: '~/tmp'
#    creates: '/usr/bin/pacaur'
#  tags:
#    - pacaur
#    - pacaur.pacaur
#
#- name: 'install pacaur'
#  shell: 'sudo pacman --noconfirm -U pacaur-4.8.5-1-any.pkg.tar.xz'
#  args:
#    chdir: '~/tmp'
#    creates: '/usr/bin/pacaur'
#  tags:
#    - pacaur
#    - pacaur.pacaur

# ---
# ---

# ---

- name: 'clone cower'
  git:
    repo: 'https://aur.archlinux.org/cower.git'
    dest: '~/tmp/cower'
    force: true

- name: 'build and install cower'
  shell: 'makepkg -si --noconfirm'
  args:
    chdir: '~/tmp/cower'

# ---

- name: 'clone auracle-git'
  git:
    repo: 'https://aur.archlinux.org/auracle-git.git'
    dest: '~/tmp/auracle-git'
    force: true

- name: 'build and install auracle-git'
  shell: 'makepkg -si --noconfirm'
  args:
    chdir: '~/tmp/auracle-git'

# ---

- name: 'ensure required groups exist'
  group:
    name: "{{ group_name }}"
    state: 'present'
    system: true
  with_items:
    - stapusr
    - stapsys
    - stapdev
  loop_control:
    loop_var: group_name

- name: 'clone systemtap'
  git:
    repo: 'https://aur.archlinux.org/systemtap.git'
    dest: '~/tmp/systemtap'
    force: true

- name: 'build and install systemtap'
  shell: 'makepkg -si --noconfirm'
  args:
    chdir: '~/tmp/systemtap'

# ---

- name: 'clone pcp'
  git:
    repo: 'https://aur.archlinux.org/pcp.git'
    dest: '~/tmp/pcp'
    force: true

- name: 'build and install pcp'
  shell: 'makepkg -si --noconfirm'
  args:
    chdir: '~/tmp/pcp'

# ---

- name: 'clone pacaur'
  git:
    repo: 'https://aur.archlinux.org/pacaur.git'
    dest: '~/tmp/pacaur'

- name: 'build and install pacaur'
  shell: 'makepkg -si --noconfirm'
  args:
    chdir: '~/tmp/pacaur'

