# ---

- name: 'install pacaur prerequisites'
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pacaur_packages }}"
  tags:
    - pacaur
    - pacaur.prerequisites

- name: 'create pod2man symlink'
  file:
    src: '/usr/bin/core_perl/pod2man'
    dest: '/usr/local/bin/pod2man'
    state: 'link'
  tags:
    - pacaur
    - pacaur.pod2man

# ---

- name: 'build pacaur'
  become_user: ansible
  include: "./build.yml"
  tags:
    - pacaur
    - pacaur.build
