---

fs_packages:
  - mkinitcpio


fs_layout:

  # Devices specifications
  devices:
    - dev: /dev/sda
      label: gpt
    - dev: /dev/sdb
      label: gpt
    - dev: /dev/sdc
      label: gpt
    - dev: /dev/sdd
      label: gpt

  # Arrays declarations
  arrays:
    # /boot
    - name: md1
      dev: /dev/md1
      mountpoint: /mnt/md2
      devices:
        - /dev/sda1
        - /dev/sdb1
        - /dev/sdc1
        - /dev/sdd1
    # /boot/efi
    - name: md2
      dev: /dev/md2
      mountpoint: /mnt/md2
      devices:
        - /dev/sda2
        - /dev/sdb2
        - /dev/sdc2
        - /dev/sdd2
    # /
    - name: md3
      dev: /dev/md3
      mountpoint: /mnt/md3
      devices:
        - /dev/sda3
        - /dev/sdb3
        - /dev/sdc3
        - /dev/sdd3
