# ---

- name: 'install sudo prerequisites'
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sudo_packages }}"
  tags:
    - sudo
    - sudo.install

# ---

- name: 'copy /etc/sudoers'
  template:
    src: etc/sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
  tags:
    - sudo
    - sudo.sudoers

# ---

- name: 'make sure "wheel" group exists'
  group:
    name: wheel
    state: present
  tags:
      - sudo
      - sudo.group
