---

- name: install rsync
  package:
    name: rsync
    state: present

- name: create minikube user
  user:
    name: "{{ minikube_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    system: yes
    state: present

- name: create minikube local bin dir
  file:
    path: "/{{ minikube_user_home }}/.bin"
    state: directory
    owner: "{{ minikube_user }}"
    mode: 0775
    recurse: yes

- name: create minikube temp dir
  file:
    path: "{{ minikube_user_tmp }}"
    state: directory
    owner: "{{ minikube_user }}"
    mode: 0775
    recurse: yes

- name: download minikube
  get_url:
    url: "{{ minikube_url }}"
    dest: "{{ minikube_user_tmp }}/minikube"
    owner: "{{ minikube_user }}"
    mode: "u+rwx"

#- name: move downloaded minikube
#  synchronize:
#    src: "{{ minikube_user_tmp }}/minikube"
#    dest:  "{{ minikube_user_home }}/.bin/"
