---

# https://docs.ansible.com/ansible/latest/modules/parted_module.html

- name: print disk info
  block:
    - command: "fdisk -l {{ item }}"
      with_items:
        - "{{ fs_devices }}"

- name: print disk info
  block:
    # Create a new primary partition with a size of 1GiB
    - parted:
        device: "{{ item }}"
        number: "{{ idx + 1 }}"
        state: present
        part_start: 1MiB
        part_end: 256MiB
      loop: "{{ fs_devices }}"
      loop_control:
        index_var: idx

#- name: mdadm
#  include_role:
#    name: ansible-mdadm
#  vars:
#    - mdadm_arrays:
#      - name: 'md0'
#        # Define disk devices to assign to array
#        devices: "{{ fs_devices }}"
#        filesystem: 'ext4'
#        state: 'present'

#- name: mdadm
#  mdadm_arrays:
#    # Define array name
#    - name: 'md0'
#      # Define disk devices to assign to array
#      devices:
#        - '/dev/sdb'
#        - '/dev/sdc'
#      # Define filesystem to partition array with
#      filesystem: 'ext4'
#      filesystem_opts: ''
#      # Define the array raid level
#      # 0|1|4|5|6|10
#      level: '1'
#      # Define mountpoint for array device
#      mountpoint: '/mnt/md0'
#      # Define if array should be present or absent
#      state: 'present'
#      # Set mount options (optional)
#      opts: 'noatime'
#    # - name: 'md0'
#    #   devices:
#    #     - '/dev/sdb'
#    #     - '/dev/sdc'
#    #     - '/dev/sdd'
#    #   filesystem: 'ext4'
#    #   level: '5'
#    #   mountpoint: '/mnt/md0'
#    #   state: 'present'
#    -
# Read device information (always use unit when probing)
#- parted: device=/dev/sdb unit=MiB
#  register: sdb_info

#- name: print disk info
#  block:
#    - command: "fdisk -l {{ item }}"
#      with_items:
#        - "{{ fs_devices }}"
#
#- name: create partition
#  parted:
#    device: /dev/sda
#    number: 1
#    state: present
#    part_end: 1GiB

## Read device information (always use unit when probing)
#- parted: device=/dev/sda unit=MiB
#  register: sda_info
#
## Remove all partitions from disk
#- parted:
#    device: /dev/sda
#    number: "{{ item.num }}"
#    state: absent
#  with_items:
#    - "{{ sda_info.partitions }}"

## Create a new primary partition
#- parted:
#    device: /dev/sda
#    number: 1
#    state: present
