# ---

- name: 'disks configuration'
  debug: msg="{{ disks }}"

- name: 'arrays configuration'
  debug: msg="{{ arrays }}"

- name: 'lvm configuration'
  debug: msg="{{ lvm }}"

- name: 'mounts configuration'
  debug: msg="{{ mounts }}"

# ---

- block:
  - name: 'cleanup mounts'
    include: "./mounts-cleanup.yml mounts={{ mounts }}"
    tags:
      - clean
      - mounts
      - mounts.clean

- block:
  - name: 'cleanup lvm'
    include: "./lvm-cleanup.yml lvm={{ lvm }}"
    tags:
      - clean
      - lvm
      - lvm.clean

- block:
  - name: 'cleanup md'
    include: "./md-cleanup.yml arrays={{ arrays }}"
    tags:
      - clean
      - md
      - md.clean
    ignore_errors: true

#- block:
#  - name: 'cleanup md'
#    include: "./md-cleanup.yml"
#    with_items: "{{ arrays }}"
#    loop_control:
#      loop_var: md
#    tags:
#      - md
#      - md.clean

- block:
  - name: 'cleanup parts'
    include: "./parts-cleanup.yml disk={{ disk }}"
    with_items: "{{ disks }}"
    loop_control:
      loop_var: disk
    tags:
      - clean
      - parts
      - parts.clean

# --

- block:
  - name: 'init parts'
    include: "./parts-init.yml"
    with_items: "{{ disks }}"
    loop_control:
      loop_var: disk
    tags:
      - init
      - parts
      - parts.init

- block:
  - name: 'init md'
    include: "./md-init.yml arrays={{ arrays }}"
    tags:
      - init
      - md
      - md.init

- block:
  - name: 'init lvm'
    include: "./lvm-init.yml lvm={{ lvm }}"
    tags:
      - init
      - lvm
      - lvm.init

- name: 'init mounts'
  include: "./mounts-init.yml mounts={{ setup_layout.mounts }}"
  tags:
    - init
    - mounts
    - mounts.init
