## ---

- name: 'install cockpit prerequisites'
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ cockpit_packages }}"
  tags:
    - cockpit

# ---

- name: 'import required gpg keys'
  become_user: ansible
  shell: "gpg --recv-keys --yes {{ item }}"
  with_items:
    - '7E83610126DCC2E8'
  tags:
    - cockpit

# ---

#- name: 'install storaged'
#  become_user: ansible
#  aur:
#    use: pacaur
#    name: storaged
#  tags:
#    - cockpit

#- name: 'ensure "storaged" service is up and running'
#  service:
#    name: storaged
#    state: restarted
#    enabled: true
#  tags:
#      - cockpit

# ---

- name: 'install "tuned" using pacaur'
  become_user: ansible
  aur:
    use: pacaur
    name: tuned-git
  tags:
    - cockpit

- name: 'ensure "tuned" service is up and running'
  service:
    name: tuned
    state: restarted
    enabled: true
  tags:
      - cockpit

# ---

- name: 'ensure "NetworkManager" service is up and running'
  service:
    name: NetworkManager
    state: restarted
    enabled: true
  tags:
      - cockpit

# ---

- name: 'install "sos" using pacaur'
  become_user: ansible
  aur:
    use: pacaur
    name: sos
  tags:
    - cockpit

# ---

- name: 'install "cockpit" using pacaur'
  become_user: ansible
  aur:
    use: pacaur
    name: cockpit
  tags:
    - cockpit

# ---

## REFERENCES
##
## - https://aur.archlinux.org/packages/cockpit-minimal/
## - https://aur.archlinux.org/packages/cockpit-git/

- name: 'create symlink'
  file:
    src: '/etc/pam.d/sshd'
    dest: '/etc/pam.d/cockpit'
    state: 'link'
  tags:
    - cockpit

# ---

#- name: 'copy /etc/pam.d/sshd -> /etc/pam.d/cockpit'
#  command: 'cp /etc/pam.d/sshd /etc/pam.d/cockpit'
#  tags:
#    - cockpit

# ---

- name: 'ensure "cockpit" service is up and running'
  service:
    name: cockpit.socket
    state: restarted
    enabled: true
  tags:
      - cockpit
