# ---

- name: 'install desktop packages'
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ desktop_packages }}"
  tags:
    - desktop

# ---

- name: 'ensure "	sddm" service is up and running'
  service:
    name: 	sddm
    state: restarted
    enabled: true
  tags:
      - desktop