---

- debug: msg='arrays-init'

- name: 'create arrays'
  include_role:
    name: ansible-mdadm
  vars:
    mdadm_arrays:
      - name: 'md3'
        devices:
          - '/dev/sda3'
          - '/dev/sdb3'
          - '/dev/sdc3'
          - '/dev/sdd3'
        filesystem: 'ext4'
        filesystem_opts: '-f -L root'
        level: '10'
        # mountpoint: '/mnt'
        state: 'present'
        # force: true

      - name: 'md2'
        devices:
          - '/dev/sda2'
          - '/dev/sdb2'
          - '/dev/sdc2'
          - '/dev/sdd2'
        filesystem: 'ext4'
        filesystem_opts: '-f -L boot'
        level: '1'
        # mountpoint: '/mnt/boot'
        state: 'present'
        # force: true

      - name: 'md1'
        devices:
          - '/dev/sda1'
          - '/dev/sdb1'
          - '/dev/sdc1'
          - '/dev/sdd1'
        filesystem: 'vfat'
        filesystem_opts: '-F32 -n efi'
        level: '1'
        # mountpoint: '/mnt/boot/efi'
        state: 'present'
        # force: true

- name: 'format /dev/md2'
  filesystem:
    fstype: ext4
    force: yes
    dev: '/dev/md2'

- name: 'format /dev/md1s'
  filesystem:
    fstype: vfat
    force: yes
    dev: '/dev/md1'

- name: 'probe disks'
  shell: "partprobe /dev/sd{a,b,c,d}"
