---

- debug: msg='running setup'

- debug: msg="disks {{setup_layout}}"

- name: 'install core host prerequisites/packages'
  include: "./install-host-prerequisites.yml"

- name: 'unmount'
  include: "./mounts-cleanup.yml mounts={{ setup_layout.mounts | reverse | list }}"

- name: 'cleanup lvm'
  include: "./lvm-cleanup.yml"

- name: 'cleanup arrays'
  include: "./arrays-cleanup.yml arrays={{ setup_layout.arrays }}"

- name: 'cleanup disks'
  include: "./disks-cleanup.yml disks={{ setup_layout.disks }}"

- name: 'init disks'
  include: "./disks-init.yml disks={{ setup_layout.disks }}"

# ---


#- name: 'init arrays'
#  include: "./arrays-init.yml arrays={{ setup_layout.arrays }}"
#
#- name: 'init lvm'
#  include: "./lvm-init.yml"
#
#- name: 'mount'
#  include: "./mounts-init.yml mounts={{ setup_layout.mounts }}"


# ---

# - name: 'install base'
#  include: "./install-base.yml"

# ---
#
#- name: 'install guest'
#  include: "./install-guest.yml"
#
# ---
#
#- name: 'reboot machine'
#  reboot:
#    reboot_timeout: 900
