- hosts: all
  become: yes
  gather_facts: yes
  remote_user: root
  debugger: never # always | never | on_failed | on_unreachable | on_skipped
  roles:
    - os                # Upgrade system
    - core              # Core system packages
    - base              # Base tools - tmux, mosh, ...
    - fail2ban
    - users
    - pacaur
    - docker
    - docker-registry
    - kubernetes
    - cockpit
    - desktop
