---

setup_layout:
  core_host_packages:
    - git
    - htop
    - mc
    - tmux
    - vim

  core_host_packages_old:
    # - ansible
    # - arch-install-scripts
    - archiso
    # - bonnie++
    # - dosfstools
    - efibootmgr
    - efitools
    - efivar
    - expac
    # - findutils
    - fwupd
    # - gdisk
    - git
    - gnupg
    - hdparm
    - hwinfo
    - htop
    # - linux-headers
    # - linux-tools
    - mc
    # - mkinitcpio
    - mosh
    - openssh
    - openssl
    # - parted
    # - sbsigntools
    # - sysfsutils
    - sudo
    - tmux
    # - usbip
    - vim
    - yajl
#    - imagemagick
#    - jq
#    - kexec-tools
#    - linux-tools
#    - refind-efi
#    - ucode-intel
#    - udisk2

  core_guest_packages:
    - base
    - base-devel
    - ansible
    - arch-install-scripts
    - archiso
    - efibootmgr
    - efitools
    - efivar
    - fwupd
    - git
    - grub
    - htop
    # - kexec-tools
    - linux
    - linux-headers
    - linux-tools
    - mc
    - mosh
    - openssh
    - perl
    - python
    # - sbsigntools
    - sudo
    - tmux

  disks:
    - device: '/dev/sde'
      label: 'gpt'
      parts:
        - name: 'EFI'
          filesystem: 'vfat'
          filesystem_opts: '-F 32 -n EFI'
          part_start: '1MiB'
          part_end: '1GiB'
          flags: [ boot, esp ]
          force: true
        - name: 'boot'
          filesystem: 'ext4'
          filesystem_opts: '-L boot'
          part_start: '1GiB'
          part_end: '2GiB'
          flags: []
          force: true
        - name: 'root'
          filesystem: 'ext4'
          filesystem_opts: '-L root'
          part_start: '2GiB'
          part_end: '100%'
          flags: []
          force: true
  mounts:
    - path: '/mnt'
      fstype: auto
      src: "LABEL=root"
    - path: '/mnt/boot'
      fstype: auto
      src: "LABEL=boot"
    - path: '/mnt/boot/efi'
      fstype: auto
      src: "LABEL=EFI"
